version: '3.3'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'

    environment:
      MYSQL_DATABASE: 'gympower'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'