version: '3.3'
services:
  db:
    image: arm64v8/mysql:oracle
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_DATABASE=gympower
  gympower:
    image: eneschelebi03/gympower
    depends_on: [db]
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Shadow887!