spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: gympower_database_user
    url: jdbc:postgresql://${POSTGRES_URL}:5432/gympower_database
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
  tomcat:
    accesslog:
      enabled: 'true'