spring:
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      password: Shadow887!
#      url: jdbc:mysql://gympower-db.cug9cgnskdxn.eu-north-1.rds.amazonaws.com:3306/gympower?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#      username: admin
      url: jdbc:mysql://localhost:3306/gympower?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
      username: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always