package com.example.gympower.model.enums;

public enum FlavorEnum {
    EXTREME_MILK_CHOCOLATE,
    DOUBLE_RICH_CHOCOLATE,
    COOKIES_CREAM,
    VANILLA_ICE_CREAM,
    GHOST_WHEY,
    MOCHA_CAPPUCCINO,
    FRENCH_VANILLA,
    BANANA_CREME,
    CHOCOLATE_MALT,
    DONT_KNOW,
    STRAWBERRY_BANANA,
    DELICIOUS_STRAWBERRY,
    CARAMEL_TOFFEE_FUDGE,
    CHOCOLATE_PEANUT_BUTTER,
    FRENCH_VANILLA_CREME,
    MANGO
}
