package com.example.gympower.model.entity.enums;

public enum FlavorEnum {
    EXTREME_MILK_CHOCOLATE,
    DOUBLE_RICH_CHOCOLATE,
    COOKIES_CREAM,
    VANILLA_ICE_CREAM,
    GHOST_WHEY,
    MOCHA_CAPPUCCINO,
    FRENCH_VANILLA,
    BANANA_CREME,
    CHOCOLATE_MALT,
    DONT_KNOW,
    STRAWBERRY_BANANA,
    DELICIOUS_STRAWBERRY,
    CARAMEL_TOFFEE_FUDGE,
    CHOCOLATE_PEANUT_BUTTER,
    FRENCH_VANILLA_CREME,
    MANGO,

    CHOCOLATE,
    BANANA,
    BISCUITS_WITH_CREAM,
    DOUBLE_CHOCOLATE,
    WHITE_CHOCOLATE_WITH_HAZELNUTS
}
